### ISSUE TITLE
misc: Update Python syntax

### ISSUE THREAD

**Issue by kingiler** [xdslproject/xdsl#1250]
As we are using latest two Python versions, many code written years before can be upgrade to use the newest syntax for readability and performance. Since the upgrade is huge, I propose to upgrade in phrase by a series of PRs.

- [x] Upgrade to Python 3.8+
  - [x] Redundant ```r``` mode in ```open``` #1249 
  - [x] Use ```f-string``` instead of ```.format``` or ```%``` #1251
  - [x] Use generator, or direct syntax. #1252 
  - [x] Update typing hint
- [x] Upgrade to Python 3.9+
  - [x] PEP 585 typing rewrites (https://peps.python.org/pep-0585/)
- [x] Upgrade to Python 3.10+
  - [x] PEP 604 typing rewrites (https://peps.python.org/pep-0604/)

**Comment by compor** [comment]
In general, I'm fine with this, I just don't see the pressing need for
this, unless we're doing a "lint party" or similar.

I prefer doing that once the code is touched in the course of other
feature-rich PRs.

**Comment by superlopuh** [comment]
I agree, I'm a big fan of these changes iff all other functional work is blocked in one way or another.

**Comment by kingiler** [comment]
Addressed in latest commit.
